name: "Run phpcs and phpmd"
description: "Run phpcs and phpmd to check your code"
author: "Duc Anh (ducla)"
inputs:
  phpcs_args:
    description: "Arguments to pass to phpcs"
    default: "."
    required: false
  phpmd_args:
    description: "Arguments to pass to phpmd"
    default: "."
    required: false
  directory:
    description: "The subdirectory to execute the action in."
    default: "."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.phpcs_args }}
    - ${{ inputs.phpmd_args }}
    - ${{ inputs.directory }}
branding:
  icon: "edit"
  color: "gray-dark"
